#!/bin/bash
clear

# Definición de colores
msgi() {
    BLANCO='\033[1;37m'
    ROJO='\033[1;31m'
    VERDE='\033[1;32m'
    AMARELO='\033[1;33m'
    AZUL='\033[1;34m'
    MAGENTA='\033[1;35m'
    MAG='\033[1;36m'
    NEGRITA='\033[1m'
    SINCOLOR='\033[0m'
    
    case $1 in
        -ne) cor="${ROJO}${NEGRITA}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
        -ama) cor="${AMARELO}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
        -verm) cor="${AMARELO}${NEGRITA}[!] ${ROJO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
        -azu) cor="${MAG}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
        -verd) cor="${VERDE}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
        -bra) cor="${ROJO}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
        "-bar2" | "-bar")
            # Barra de colores alternos
            ccor=""
            colores=("${ROJO}" "${VERDE}" "${AMARELO}" "${AZUL}" "${MAGENTA}" "${MAG}") # Colores alternos
            for ((i=0; i<50; i++)); do
                color_index=$((i % ${#colores[@]})) # Alterna entre los colores
                ccor+="${colores[$color_index]}═"
            done
            echo -e "${SINCOLOR}${ccor}${SINCOLOR}"
        ;;
    esac
}


# Función para instalar dependencias
dependencias() {
    dpkg --configure -a >/dev/null 2>&1
    apt -f install -y >/dev/null 2>&1
    export DEBIAN_FRONTEND=noninteractive
    soft="sudo bsdmainutils zip screen unzip ufw curl python python3 python3-pip openssl cron iptables lsof pv boxes at mlocate gawk bc jq curl npm nodejs socat netcat netcat-traditional net-tools cowsay figlet lolcat apache2"

    # Contar el número total de paquetes a instalar
    total=$(echo "$soft" | wc -w)
    count=0

    for i in $soft; do
        if ! dpkg -s "$i" >/dev/null 2>&1; then
            echo -ne "\e[1;97m        Instalando \e[93m $i ... \e[0m"
            apt-get install "$i" -y >/dev/null 2>&1
            count=$((count + 1))
            percent=$((count * 100 / total))
            echo -ne "\r\e[1;97m        Instalando paquetes... \e[1;32m[$percent%]\e[0m"
        fi
    done

    echo -e "\n\e[1;32m        Instalación completada.\e[0m"
}

# Función para instalar paquetes y configurar Apache
install_paquetes() {
    clear && clear
    /bin/cp /etc/skel/.bashrc ~/
    msgi -bar2
    echo -e " \e[5m\e[1;100m   =====>> ►►     script v6     ◄◄ <<=====    \e[1;37m"
    msgi -bar
    echo -e "   \e[1;41m    -- INSTALACION PAQUETES FALTANTES --    \e[49m"
    msgi -bar
    dependencias
    sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf >/dev/null 2>&1
    service apache2 restart >/dev/null 2>&1
    [[ $(sudo lsof -i :81) ]] || ESTATUSP=$(echo -e "\e[1;91m      >>>  FALLO DE INSTALACION EN APACHE <<<") &>/dev/null
    [[ $(sudo lsof -i :81) ]] && ESTATUSP=$(echo -e "\e[1;92m          PUERTO APACHE ACTIVO CON EXITO") &>/dev/null
    echo ""
    echo -e "$ESTATUSP"
    echo ""
    echo -e "\e[1;97m        REMOVIENDO PAQUETES OBSOLETOS - \e[1;32m OK"
    apt autoremove -y &>/dev/null
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
    msgi -bar2
    read -t 30 -n 1 -rsp $'\e[1;97m           Presiona Enter Para continuar\n'
}

# Función para instalar el mod ChumoGH
install_ChumoGH() {
  msgi -bar2
  clear && clear
  mkdir /etc/adm-lite >/dev/null 2>&1
  cd /etc
  wget https://raw.githubusercontent.com/joaquin1444/MOD-V6/main/script-v6/adm-lite.tar.gz >/dev/null 2>&1
  tar -xf adm-lite.tar.gz >/dev/null 2>&1
  chmod +x adm-lite.tar.gz >/dev/null 2>&1
  rm -rf /etc/adm-lite.tar.gz
  cd
  chmod -R 755 /etc/adm-lite
  /bin/cp /etc/skel/.bashrc ~/
  rm -rf /etc/bash.bashrc >/dev/null 2>&1
  echo "$slogan" >/etc/adm-lite/menu_credito
  fecha=$(date +"%d-%m-%y")
  dom='base64 -d'
  SCPdir="/etc/adm-lite"
  SCPinstal="$HOME/install"
  SCPidioma="${SCPdir}"
  SCPusr="${SCPdir}"
  cd /etc/adm-lite
  echo "cd /etc/adm-lite && ./menu" >/bin/menu
  echo "cd /etc/adm-lite && ./menu" >/bin/cgh
  echo "cd /etc/adm-lite && ./menu" >/bin/adm
  chmod +x /bin/menu
  chmod +x /bin/cgh
  chmod +x /bin/adm
  cd $HOME
  echo ""
  rm -rf mkdir /bin/ejecutar >/dev/null
  [[ -e /etc/adm-lite/menu_credito ]] && ress="$(cat </etc/adm-lite/menu_credito) " || ress="NULL ( no found ) "
  chmod +x /etc/adm-lite/*
  [[ -e ${SCPinstal}/v-local.log ]] && vv="$(cat <${SCPinstal}/v-local.log)" || vv="NULL"
  #cd /etc/adm-lite && bash cabecalho --instalar
  echo "verify" >$(echo -e $(echo 2f62696e2f766572696679737973 | sed 's/../\\x&/g;s/$/ /'))
  fecha=$(date +"%d-%m-%y")

  [[ -d /bin/ejecutar ]] && rm -rf /bin/ejecutar
  [[ -e /etc/adm-lite/gerar.sh ]] && rm -f /etc/adm-lite/gerar.sh
  [[ -z $name ]] && {
    rm -f /root/name
  } || {
    echo $name >/etc/adm-lite/name
    chmod +x /etc/adm-lite/name
    echo $name >/root/name
  }
  opti=0

  /etc/adm-lite/cabecalho --instalar
  echo "verify" >$(echo -e $(echo 2f62696e2f766572696679737973 | sed 's/../\\x&/g;s/$/ /'))
  echo 'MOD @ChumoGH Joaquin 🇦🇷' >$(echo -e $(echo 2F7573722F6C69622F6C6963656E6365 | sed 's/../\\x&/g;s/$/ /'))

  echo "Verified【 Joaquin 🇦🇷  " >/bin/ejecutar/exito
  clear && clear
  msgi -bar2
  echo -e "\e[1;92m             >> INSTALACION COMPLETADA <<" && msgi -bar2
  echo -e "      COMANDO PRINCIPAL PARA ENTRAR AL PANEL "
  echo -e "                      \033[1;41m  menu  \033[0;37m" && msgi -bar2
}

os_system() {
    system=$(cat -n /etc/issue | grep 1 | cut -d ' ' -f6,7,8 | sed 's/1//' | sed 's/      //')
    distro=$(echo "$system" | awk '{print $1}')
    case $distro in
        Debian) vercion=$(echo $system | awk '{print $3}' | cut -d '.' -f1) ;;
        Ubuntu) vercion=$(echo $system | awk '{print $2}' | cut -d '.' -f1,2) ;;
    esac
}

repo() {
    link="https://raw.githubusercontent.com/joaquin1444/MOD-V6/main/Source-List/$1.list"
    wget -q -O /etc/apt/sources.list ${link}
    apt-get update -q
}

# Verificación de permisos
if [ "$(whoami)" != 'root' ]; then
    echo ""
    echo -e "\e[1;31m NECESITAS SER USER ROOT PARA EJECUTAR EL SCRIPT \n\n\e[97m                DIGITE: \e[1;32m sudo su\n"
    exit
fi

# Obtención y almacenamiento de versión
v1=$(curl -sSL "https://raw.githubusercontent.com/joaquin1444/MOD-V6/main/Vercion")
echo "$v1" >/etc/version_instalacion
v22=$(cat /etc/version_instalacion)
vesaoSCT="\e[1;31m [ \e[1;32m( $v22 )\e[1;97m\e[1;31m ]"

# Configuración del sistema y repositorios
os_system
repo "${vercion}"

# Menú de instalación
msgi -bar2
echo -e " \e[5m\e[1;100m   =====>> ►►     MENU DE INSTALACION     ◄◄ <<=====    \e[1;37m"
msgi -bar2

while :; do
    echo -ne "\e[1;93m [\e[1;32m1\e[1;93m]\e[1;31m >\e[1;97m Instalar ChumoGH mod \e[1;31m \e[97m \n"
    echo -ne "\e[1;93m [\e[1;32m0\e[1;93m]\e[1;31m >\e[1;97m Salir \e[1;31m \e[97m \n"
    msgi -bar2
    echo -ne "\e[1;97mDigite solo el numero segun su respuesta:\e[32m "
    read opcao

    case $opcao in
    clear
        1) install_ChumoGH ;;
        0) exit ;;
        *) msgi -verm "Opción no válida. Intenta de nuevo." ;;
    esac
done
